
package com.mycompany.proyecto_estacionamiento;

import javax.swing.JOptionPane;


public class CrearUsuario extends javax.swing.JPanel {

    
    public CrearUsuario() {
        initComponents();
        ComboxJuntos();
    }

    
    public void ComboxJuntos() {
    
    ComboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[]{"Seleccione el tipo","Auto", "Moto"}
    ));

    
    ComboxArea.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[]{"Seleccione el tipo","Estudiante", "Catedratico", "Moto"}
    ));
   }
    
    private String nz(Object o) {
    return (o == null) ? "" : o.toString().trim();
}

        public String normPlaca(Object p) {
            if (p == null) return "";
            return p.toString().replace("-", "").replace(" ", "").toUpperCase().trim();
        }

        public boolean existeCarne(String carne) {
            for (Usuarios u : DatosCentrales.USUARIOS) {
                if (nz(u.getCarne()).equalsIgnoreCase(carne)) return true;
            }
            return false;
        }

        public boolean existePlaca(String placaNorm) {
            for (Usuarios u : DatosCentrales.USUARIOS) {
                if (normPlaca(u.getPlaca()).equals(placaNorm)) return true;
            }
            return false;
        }

        public boolean existeVehiculo(String placaNorm) {
            for (Vehiculos v : DatosCentrales.VEHICULOS) {
                if (normPlaca(v.getPlaca()).equals(placaNorm)) return true;
            }
            return false;
        }

        public void limpiar() {
            
            TexCarne.setText("");
            TexNombre.setText("");
            TexPlaca.setText("");
            ComboxTipo.setSelectedIndex(0);
            ComboxArea.setSelectedIndex(0);
            TexCarne.requestFocus();
        }
        

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TexCarne = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        TexNombre = new javax.swing.JTextField();
        TexPlaca = new javax.swing.JTextField();
        ComboxTipo = new javax.swing.JComboBox<>();
        ComboxArea = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("CREAR USUARIO");

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        ComboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Item 2", "Item 3", "Item 4" }));
        ComboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxTipoActionPerformed(evt);
            }
        });

        ComboxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setBackground(new java.awt.Color(51, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("Carné del Usuario");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Nombre Completo");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("Placa del Vehiculo");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Tipo de Vehiculo");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Tipo de Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TexCarne)
                        .addComponent(TexNombre)
                        .addComponent(TexPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(BtnGuardar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TexCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TexNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TexPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BtnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboxTipoActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        
        String carne  = nz(TexCarne.getText());
        String nombre = nz(TexNombre.getText());
        String placa  = normPlaca(TexPlaca.getText()); // sin espacios o giones
        String tipoVehiculo = (String) ComboxTipo.getSelectedItem();
        String tipoArea     = (String) ComboxArea.getSelectedItem();

    if (carne.isEmpty() || nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Carné y nombre vacios");
        return;
    }
    if (existeCarne(carne)) {
        javax.swing.JOptionPane.showMessageDialog(this, "El carné ya existe");
        return;
    }
   
    if (!placa.isEmpty() && existePlaca(placa)) {
        javax.swing.JOptionPane.showMessageDialog(this, "La placa en uso");
        return;
    }

  
    Usuarios u = new Usuarios();   // guardar usuaioo
    u.setCarne(carne);
    u.setNombre(nombre);
    u.setPlaca(placa);      
    u.setCarrera("");       

    DatosCentrales.USUARIOS.add(u);

 
    if (!placa.isEmpty()) {  // si ingresa placse crea
      
        if (!existeVehiculo(placa)) {
            Vehiculos v = new Vehiculos();// si no existe el vehículo por placa lo creamos
            v.setPlaca(placa);
            v.setTipoVehiculo(nz(tipoVehiculo));
            v.setTipoArea(nz(tipoArea)); 
            DatosCentrales.VEHICULOS.add(v);
        }
    }
    try {
        Importar_BD.insertarUsuariosBatch(DatosCentrales.USUARIOS);
          Importar_BD.insertarVehiculosBatch(DatosCentrales.VEHICULOS);

    } catch (Exception e) {

    }
      


    javax.swing.JOptionPane.showMessageDialog(this, "Usuario guardado correctamente.");
    limpiar();
    }//GEN-LAST:event_BtnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> ComboxArea;
    private javax.swing.JComboBox<String> ComboxTipo;
    private javax.swing.JTextField TexCarne;
    private javax.swing.JTextField TexNombre;
    private javax.swing.JTextField TexPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
