
package com.mycompany.proyecto_estacionamiento;

import javax.swing.JOptionPane;


public class IngresarVehiculos extends javax.swing.JPanel {

    /**
     * Creates new form IngresarVehiculos
     */
    public IngresarVehiculos() {
        initComponents();
        ComboPago.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"EFECTIVO", "TARJETA", "TRANSFERENCIA"}));

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"DIA", "HORA"}));

        BtnGuardar.addActionListener(e -> registrarIngreso());
        
    }
    
     private void registrarIngreso() {
        String placa = TexPlaca.getText().trim().toUpperCase();
    if (placa.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una placa correcta.");
        return;
    }

    String tipoPago = ComboPago.getSelectedItem().toString();
    String tipoTarifa = ComboTipo.getSelectedItem().toString();

   
    if (DatosCentrales.TICKETSaCTIVOS.containsKey(placa)) { 
        javax.swing.JOptionPane.showMessageDialog(this, "Este vehículo ya está dentro del parqueo.");
        return;
    }

   
    Vehiculos v = DatosCentrales.buscarPorPlaca(placa);
    if (v == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "La placa no existe en los datos");
        return;
    }

    
    String idArea = DatosCentrales.areaPorNombre(v.getTipoArea());
    if (idArea == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontro el area para: " + v.getTipoArea());
        return;
    }

  
    Spots spot = DatosCentrales.SpotLibre(idArea, v.getTipoVehiculo());
    if (spot == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay espacios libres en el area " + v.getTipoArea());
        return;
    }

             
            //se crea ekl tikcet
         Ticket t = new Ticket(placa,Ticket.TipoTarifa.valueOf(tipoTarifa),  Ticket.MetodoPago.valueOf(tipoPago), v.getTipoVehiculo(), idArea,spot.getIdSpots());

        
        DatosCentrales.ocuparSpot(spot, placa, t); // ocupamos un spot y tambien registamos el tiket 
        DatosCentrales.HISTORIALdeTICKETS.add(t);

        javax.swing.JOptionPane.showMessageDialog(this, t.imprimir());

        DatosCentrales.ocuparSpot(spot, placa, t); // Ocupar el spot y registrar ticket

      javax.swing.JOptionPane.showMessageDialog(this,  "Vehículo ingresado al area" + v.getTipoArea() + "\ny Spot " + spot.getIdSpots());

 
    TexPlaca.setText("");
    ComboPago.setSelectedIndex(0);
    ComboTipo.setSelectedIndex(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TexPlaca = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ComboPago = new javax.swing.JComboBox<>();
        ComboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("INGRESAR VEHICULOS");

        jLabel2.setText("Ingrese la placa del vehiculo");

        BtnGuardar.setText("Ingresar");

        jLabel3.setText("Tipo de pago");

        ComboPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Tipo de tarifa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(BtnGuardar)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(TexPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(TexPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGuardar)
                        .addGap(53, 53, 53))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> ComboPago;
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JTextField TexPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
