
package com.mycompany.proyecto_estacionamiento;



public class IngresarVehiculos extends javax.swing.JPanel {

    /**
     * Creates new form IngresarVehiculos
     */
   
    
    
    public IngresarVehiculos() {
        initComponents();
        
        ComboPago.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"EFECTIVO", "TARJETA", "TRANSFERENCIA"}));

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"DIA", "HORA"}));

       
        
    }
    
    private void registrarIngreso() {
        
    String placaInput = TexPlaca.getText();
    String placaNorm = DatosCentrales.normalizarPlaca(placaInput);
    
            if (placaNorm.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una placa correcta.");
                return;
            }

    Ticket.MetodoPago metodo = Ticket.MetodoPago.valueOf(ComboPago.getSelectedItem().toString());
    Ticket.TipoTarifa tarifa = Ticket.TipoTarifa.valueOf(ComboTipo.getSelectedItem().toString());

    if (DatosCentrales.TICKETSaCTIVOS.containsKey(placaNorm)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Este vehiculo ya esta dentro del parqueo");
        return;
    }

    Vehiculos v = DatosCentrales.buscarPorPlaca(placaNorm);
    if (v == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "La placa no existe en los datos.");
        return;
    }

    String idArea = DatosCentrales.areaPorNombre(v.getTipoArea());
    if (idArea == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontro el area para " + v.getTipoArea());
        return;
    }

     Spots spottt = DatosCentrales.spotReservadoDePlaca(placaNorm);

        if (spottt != null) {
            
            spottt.setStatus(DatosCentrales.STATUS_OCUPADO);

    
            DatosCentrales.cancelarReservaPorPlaca(placaNorm);         // Eliminamos la reserva que ya se osuo

         
            if (tarifa == Ticket.TipoTarifa.DIA) {
                DatosCentrales.REINGRESO_DIA_SIN_COBRO.add(placaNorm);
            }

        } else {
            
            spottt = DatosCentrales.SpotLibre(idArea, v.getTipoVehiculo());
            if (spottt == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay espacios libres en el area " + v.getTipoArea());
                return;
            }
            spottt.setStatus(DatosCentrales.STATUS_OCUPADO);
        }

    Ticket t = new Ticket(
        placaNorm, tarifa, metodo,
        v.getTipoVehiculo(), idArea,
        spottt.getIdSpots()
    );

    DatosCentrales.ocuparSpot(spottt, placaNorm, t);
    DatosCentrales.HISTORIALdeTICKETS.add(t);
    
    
    
    
try (var cn = Conexion_BD.conectar(); // Guardar ticket activo en la base
     var ps = cn.prepareStatement(
         "INSERT INTO tickets_activos " +
         "(placa, area_id, spot_id, fecha_ingreso, tipo_tarifa, metodo_pago) " +
         "VALUES (?, ?, ?, ?, ?, ?) " +
         "ON DUPLICATE KEY UPDATE " +
         "area_id = VALUES(area_id), " +
         "spot_id = VALUES(spot_id), " +
         "fecha_ingreso = VALUES(fecha_ingreso), " +
         "tipo_tarifa = VALUES(tipo_tarifa), " +
         "metodo_pago = VALUES(metodo_pago)"
     )) {

    ps.setString(1, placaNorm);
    ps.setString(2, idArea);
    ps.setString(3, spottt.getIdSpots());
    ps.setTimestamp(4, java.sql.Timestamp.valueOf(t.getHoraIngreso()));
    ps.setString(5, t.getTarifa().name());
    ps.setString(6, t.getPago().name());
    ps.executeUpdate();

} catch (Exception ex) {
    System.out.println("Error al guardar ticket activo en BD: " + ex.getMessage());
}

    
    
    

   
    try (var cn = Conexion_BD.conectar(); // lo ghuarada en la base de datos
         var ps = cn.prepareStatement("UPDATE spots SET status=? WHERE area_id=? AND spot_id=?")) {
        ps.setString(1, DatosCentrales.STATUS_OCUPADO);
        ps.setString(2, spottt.getIdArea());
        ps.setString(3, spottt.getIdSpots());
        ps.executeUpdate();
    } catch (Exception ex) {
        System.out.println("Error al actualizar estado en BD: " + ex.getMessage());
    }

    

    javax.swing.JOptionPane.showMessageDialog(this, t.imprimir()); //  El mapa se actualiza solo por al Timer en panelMapa
    TexPlaca.setText("");
    ComboPago.setSelectedIndex(0);
    ComboTipo.setSelectedIndex(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TexPlaca = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ComboPago = new javax.swing.JComboBox<>();
        ComboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("INGRESAR VEHICULOS");

        jLabel2.setText("Ingrese la placa del vehiculo");

        BtnGuardar.setText("Ingresar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de pago");

        ComboPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Tipo de tarifa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(BtnGuardar)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(TexPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(TexPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGuardar)
                        .addGap(53, 53, 53))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
         registrarIngreso();
        
    }//GEN-LAST:event_BtnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> ComboPago;
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JTextField TexPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
