
package com.mycompany.proyecto_estacionamiento;

/**
 *
 * @author grija
 */
public class panelMapa extends javax.swing.JPanel {

    /**
     * Creates new form panelMapa
     */
    public panelMapa() {
        initComponents();
         
        
    new javax.swing.Timer(1000, e -> mostrarMapa()).start(); //  refresca el mapa cada segundo

     
    new javax.swing.Timer(5000, e -> { //  Cada 5 segundos libera reservasd vencidas
        
        java.time.LocalDateTime ahora = java.time.LocalDateTime.now();

        for (var entry : new java.util.HashMap<>(DatosCentrales.RESERVAunRATO).entrySet()) {
            if (ahora.isAfter(entry.getValue())) {
                String llave = entry.getKey(); // se muestra el area#spot coomo enm el archvio
                String[] p = llave.split("#");
                if (p.length != 2) continue;

                Spots s = DatosCentrales.buscarSpotIds(p[0], p[1]);
                if (s != null) {
                    s.setStatus(DatosCentrales.STATUS_LIBRE);
                    
                    try (var cn = Conexion_BD.conectar(); //  tambien wse actualiza en BD
                         var ps = cn.prepareStatement("UPDATE spots SET status='LIBRE' WHERE area_id=? AND spot_id=?")) {
                        ps.setString(1, p[0]);
                        ps.setString(2, p[1]);
                        ps.executeUpdate();
                    } catch (Exception ex) {
                        System.out.println("Error liberando reserva: " + ex.getMessage());
                    }
                }

               
                DatosCentrales.RESERVAunRATO.remove(llave);  // quita la reserva vencida
                DatosCentrales.RESERVAdePLACA.values().remove(llave);
            }
        }
    }).start();
    }

            public void mostrarMapa() {
             Mapa.refrescar(this);
         }

             public void refrescar() {
                 mostrarMapa();
             }

  
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
