/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_estacionamiento;



/**
 *
 * @author grija
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    IngresarVehiculos panelingresarvehiculo;
    RetirarVehiculos panelretirarvehiculo;
    CargarVehiculos panelcargarvehiculos;
    ListaVehiculos panellistavehiculos;
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
     
        setSize (800,450);
        panelingresarvehiculo = new IngresarVehiculos();
        panelingresarvehiculo.setBounds (300,0, 473,400);
        add (panelingresarvehiculo);
        
        panelretirarvehiculo = new RetirarVehiculos();
        panelretirarvehiculo.setBounds (300,0,473, 400);
        add (panelretirarvehiculo);
        
        panelcargarvehiculos = new CargarVehiculos();
        panelcargarvehiculos.setBounds (300,0,473, 400);
        add (panelcargarvehiculos);
        
        panellistavehiculos = new ListaVehiculos();
        panellistavehiculos.setBounds (300,0,473, 400);
        add (panellistavehiculos);
        
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);  
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVehiculos = new javax.swing.JMenu();
        menuIngresarvechiculo = new javax.swing.JMenuItem();
        menuRetirtarvehiculo = new javax.swing.JMenuItem();
        MenuCrearUsuario = new javax.swing.JMenuItem();
        menuArchivos = new javax.swing.JMenu();
        menuListado = new javax.swing.JMenuItem();
        menuCargar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PARQUEO UMG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);

        menuVehiculos.setText("Vehiculos");

        menuIngresarvechiculo.setText("Ingresar Vehiculo");
        menuIngresarvechiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarvechiculoActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuIngresarvechiculo);

        menuRetirtarvehiculo.setText("Retirar Vehiculo");
        menuRetirtarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRetirtarvehiculoActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuRetirtarvehiculo);

        MenuCrearUsuario.setText("Crear nuevo Usuario");
        MenuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearUsuarioActionPerformed(evt);
            }
        });
        menuVehiculos.add(MenuCrearUsuario);

        jMenuBar1.add(menuVehiculos);

        menuArchivos.setText("Archivos");

        menuListado.setText("Lista de vehiculos");
        menuListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoActionPerformed(evt);
            }
        });
        menuArchivos.add(menuListado);

        menuCargar.setText("Cargar datos");
        menuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCargarActionPerformed(evt);
            }
        });
        menuArchivos.add(menuCargar);

        jMenuBar1.add(menuArchivos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(483, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIngresarvechiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarvechiculoActionPerformed
        // TODO add your handling code here:
        
        setSize (800,450);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(true);
        
        
        
    }//GEN-LAST:event_menuIngresarvechiculoActionPerformed

    private void menuRetirtarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRetirtarvehiculoActionPerformed
        // TODO add your handling code here:
        setSize (800,450);
        panelretirarvehiculo.setVisible(true);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
        
    }//GEN-LAST:event_menuRetirtarvehiculoActionPerformed

    private void menuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargarActionPerformed
        // TODO add your handling code here:
        setSize (800,450);
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(true);
        panellistavehiculos.setVisible(false);
    }//GEN-LAST:event_menuCargarActionPerformed

    private void menuListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoActionPerformed
        // TODO add your handling code here:
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(true);
    }//GEN-LAST:event_menuListadoActionPerformed

    private void MenuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuArchivos;
    private javax.swing.JMenuItem menuCargar;
    private javax.swing.JMenuItem menuIngresarvechiculo;
    private javax.swing.JMenuItem menuListado;
    private javax.swing.JMenuItem menuRetirtarvehiculo;
    private javax.swing.JMenu menuVehiculos;
    // End of variables declaration//GEN-END:variables
}
