
package com.mycompany.proyecto_estacionamiento;


import java.awt.Graphics;
import java.awt.Graphics2D;
import java.time.LocalDateTime;




public class Principal extends javax.swing.JFrame {
    
    private final javax.swing.JPanel areaTrasnparente;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    IngresarVehiculos panelingresarvehiculo;
    RetirarVehiculos panelretirarvehiculo;
    CargarVehiculos panelcargarvehiculos;
    ListaVehiculos panellistavehiculos;
    CrearUsuario panelcrearCrearUsuario;
    
    public Principal() {
       initComponents();
        setLocationRelativeTo(null);
        setSize(800, 450);
        
         
        Descargar_BD.cargarUsuarios(); // descarga de la bse para tener los datos listos
        Descargar_BD.cargarAreas();
        Descargar_BD.cargarSpots();
        Descargar_BD.cargarTicketsActivos();
        Descargar_BD.cargarVehiculos();
        liberarReservasVencidas();
        Descargar_BD.cargarHistorico();
      
        

    
        areaTrasnparente = new javax.swing.JPanel(null) {
            { 
        
        setOpaque(false);
    }
    @Override
    protected void paintComponent(Graphics g) {
        

        Graphics2D g2 = (Graphics2D) g.create();
        g2.setColor(new java.awt.Color(255, 255, 255, 80)); 
        g2.fillRect(0, 0, getWidth(), getHeight());

     
        g2.dispose();
            }
        };
        
        areaTrasnparente.setBounds(300, 0, 473, 400);
        
        getContentPane().add(areaTrasnparente);

        
        getContentPane().setComponentZOrder(areaTrasnparente, 0); //  0rden de capas
        
        getContentPane().setComponentZOrder(fondoxd, getContentPane().getComponentCount() - 1);

        
        panelingresarvehiculo = new IngresarVehiculos(); //  póner paneles y agregarlos dentrro del tranapaarente
        panelretirarvehiculo  = new RetirarVehiculos();
        panelcargarvehiculos  = new CargarVehiculos();
        panellistavehiculos   = new ListaVehiculos();
        panelcrearCrearUsuario= new CrearUsuario();

     
        panelingresarvehiculo.setOpaque(false);    //  para que se vea el fondo a 
        panelretirarvehiculo.setOpaque(false);
        panelcargarvehiculos.setOpaque(false);
        panellistavehiculos.setOpaque(false);
        panelcrearCrearUsuario.setOpaque(false);

        for (java.awt.Component c : new java.awt.Component[]{
            
                panelingresarvehiculo, panelretirarvehiculo,
            
                panelcargarvehiculos, panellistavehiculos, panelcrearCrearUsuario}) {
            
            c.setBounds(0, 0, 473, 400);
            areaTrasnparente.add(c);    
            
            c.setVisible(false);
        }

        getContentPane().revalidate();
        getContentPane().repaint();
    }
    
    
    
    public static void liberarReservasVencidas() {
        
    LocalDateTime ahora = LocalDateTime.now();

   
    for (Spots s : DatosCentrales.SPOTS) {  // buscamos en todos los spots

       
        String Llavecita = DatosCentrales.Spotllave(s.getIdArea(), s.getIdSpots());   // mir si esta resercado o tiene un rato 
        
        LocalDateTime vence = DatosCentrales.RESERVAunRATO.get(Llavecita);

        if (DatosCentrales.STATUS_RESERVADO.equalsIgnoreCase(s.getStatus())) { // si ya se vencio

            
            if (vence != null && ahora.isAfter(vence)) {
                s.setStatus(DatosCentrales.STATUS_LIBRE);
                DatosCentrales.actualizarEstadoSpotEnBD(s.getIdArea(), s.getIdSpots(), DatosCentrales.STATUS_LIBRE);
                DatosCentrales.RESERVAunRATO.remove(Llavecita);
                DatosCentrales.RESERVAdePLACA.values().remove(Llavecita);
            }

           
            if (vence == null) {
                s.setStatus(DatosCentrales.STATUS_LIBRE);   // al reiniciarse se actualiza y que se quitn
                DatosCentrales.actualizarEstadoSpotEnBD(s.getIdArea(), s.getIdSpots(), DatosCentrales.STATUS_LIBRE);
            }
        }
    }
}


    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoxd = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVehiculos = new javax.swing.JMenu();
        menuIngresarvechiculo = new javax.swing.JMenuItem();
        menuRetirtarvehiculo = new javax.swing.JMenuItem();
        MenuCrearUsuario = new javax.swing.JMenuItem();
        menuArchivos = new javax.swing.JMenu();
        menuListado = new javax.swing.JMenuItem();
        menuCargar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuMapa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoxd.setBackground(new java.awt.Color(255, 255, 255));
        fondoxd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N

        jMenuBar1.setBorder(null);

        menuVehiculos.setText("Vehiculos");

        menuIngresarvechiculo.setText("Ingresar Vehiculo");
        menuIngresarvechiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarvechiculoActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuIngresarvechiculo);

        menuRetirtarvehiculo.setText("Retirar Vehiculo");
        menuRetirtarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRetirtarvehiculoActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuRetirtarvehiculo);

        MenuCrearUsuario.setText("Crear nuevo Usuario");
        MenuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearUsuarioActionPerformed(evt);
            }
        });
        menuVehiculos.add(MenuCrearUsuario);

        jMenuBar1.add(menuVehiculos);

        menuArchivos.setText("Archivos");

        menuListado.setText("Vista de datos");
        menuListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoActionPerformed(evt);
            }
        });
        menuArchivos.add(menuListado);

        menuCargar.setText("Cargar datos");
        menuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCargarActionPerformed(evt);
            }
        });
        menuArchivos.add(menuCargar);

        jMenuBar1.add(menuArchivos);

        jMenu3.setText("Mapa de Spots");

        MenuMapa.setText("Ver mapa");
        MenuMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMapaActionPerformed(evt);
            }
        });
        jMenu3.add(MenuMapa);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoxd, javax.swing.GroupLayout.PREFERRED_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoxd, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIngresarvechiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarvechiculoActionPerformed
        // TODO add your handling code here:
        
        setSize (800,450);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(true);
        panelcrearCrearUsuario.setVisible(false);
        
        
        
    }//GEN-LAST:event_menuIngresarvechiculoActionPerformed

    private void menuRetirtarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRetirtarvehiculoActionPerformed
        // TODO add your handling code here:
        setSize (800,450);
        panelretirarvehiculo.setVisible(true);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
        panelcrearCrearUsuario.setVisible(false);
        
    }//GEN-LAST:event_menuRetirtarvehiculoActionPerformed

    private void menuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargarActionPerformed
        // TODO add your handling code here:
        setSize (800,450);
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(true);
        panellistavehiculos.setVisible(false);
        panelcrearCrearUsuario.setVisible(false);
    }//GEN-LAST:event_menuCargarActionPerformed

    private void menuListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoActionPerformed
        // TODO add your handling code here:
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(true);
        panelcrearCrearUsuario.setVisible(false);
    }//GEN-LAST:event_menuListadoActionPerformed

    private void MenuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearUsuarioActionPerformed
        // TODO add your handling code here:
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
        panelcrearCrearUsuario.setVisible(true);
    }//GEN-LAST:event_MenuCrearUsuarioActionPerformed

    private void MenuMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMapaActionPerformed
        // TODO add your handling code here:
        
     Descargar_BD.cargarSpots();

    // (debug) ver cuántos spots vienen
    System.out.println("SPOTS cargados: " + DatosCentrales.SPOTS.size());

    // 2) Crear y pintar panel
    panelMapa mapa = new panelMapa();
    mapa.mostrarMapa();

    // 3) Mostrar
    javax.swing.JDialog dlg = new javax.swing.JDialog(this, "Mapa de parqueo", true);
    dlg.setContentPane(new javax.swing.JScrollPane(mapa));
    dlg.setSize(900, 600);
    dlg.setLocationRelativeTo(this);
    dlg.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_MenuMapaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCrearUsuario;
    private javax.swing.JMenuItem MenuMapa;
    private javax.swing.JLabel fondoxd;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArchivos;
    private javax.swing.JMenuItem menuCargar;
    private javax.swing.JMenuItem menuIngresarvechiculo;
    private javax.swing.JMenuItem menuListado;
    private javax.swing.JMenuItem menuRetirtarvehiculo;
    private javax.swing.JMenu menuVehiculos;
    // End of variables declaration//GEN-END:variables

    


    
}
