
package com.mycompany.proyecto_estacionamiento;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;




public class Principal extends javax.swing.JFrame {
    
    private javax.swing.JPanel areaTrasnparente;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    IngresarVehiculos panelingresarvehiculo;
    RetirarVehiculos panelretirarvehiculo;
    CargarVehiculos panelcargarvehiculos;
    ListaVehiculos panellistavehiculos;
    CrearUsuario panelcrearCrearUsuario;
    
    public Principal() {
       initComponents();
        setLocationRelativeTo(null);
        setSize(800, 450);

    
        areaTrasnparente = new javax.swing.JPanel(null) {
            { 
        // IMPORTANTE: que NO sea opaco
        setOpaque(false);
    }
    @Override
    protected void paintComponent(Graphics g) {
        // NO llenes el fondo con super si fuera opaco;
        // con opaque=false, super ya no pinta un fondo sólido.
        // super.paintComponent(g);  // <- puedes omitirlo

        Graphics2D g2 = (Graphics2D) g.create();
        // Opción A: color con alpha
        g2.setColor(new java.awt.Color(255, 255, 255, 80)); // ajusta 0..255
        g2.fillRect(0, 0, getWidth(), getHeight());

        // (Opcional) Opción B: usar AlphaComposite (equivalente):
        // g2.setComposite(java.awt.AlphaComposite.SrcOver.derive(0.6f)); // 60% opaco
        // g2.setColor(java.awt.Color.WHITE);
        // g2.fillRect(0, 0, getWidth(), getHeight());

        g2.dispose();
            }
        };
        
        areaTrasnparente.setBounds(300, 0, 473, 400);
        
        getContentPane().add(areaTrasnparente);

        
        getContentPane().setComponentZOrder(areaTrasnparente, 0); //  0rden de capas
        
        getContentPane().setComponentZOrder(fondoxd, getContentPane().getComponentCount() - 1);

        
        panelingresarvehiculo = new IngresarVehiculos(); //  póner paneles y agregarlos dentrro del tranapaarente
        panelretirarvehiculo  = new RetirarVehiculos();
        panelcargarvehiculos  = new CargarVehiculos();
        panellistavehiculos   = new ListaVehiculos();
        panelcrearCrearUsuario= new CrearUsuario();

     
        panelingresarvehiculo.setOpaque(false);    //  para que se vea el fondo a 
        panelretirarvehiculo.setOpaque(false);
        panelcargarvehiculos.setOpaque(false);
        panellistavehiculos.setOpaque(false);
        panelcrearCrearUsuario.setOpaque(false);

        for (java.awt.Component c : new java.awt.Component[]{
            
                panelingresarvehiculo, panelretirarvehiculo,
            
                panelcargarvehiculos, panellistavehiculos, panelcrearCrearUsuario}) {
            
            c.setBounds(0, 0, 473, 400);
            areaTrasnparente.add(c);    
            
            c.setVisible(false);
        }

        getContentPane().revalidate();
        getContentPane().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoxd = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVehiculos = new javax.swing.JMenu();
        menuIngresarvechiculo = new javax.swing.JMenuItem();
        menuRetirtarvehiculo = new javax.swing.JMenuItem();
        MenuCrearUsuario = new javax.swing.JMenuItem();
        menuArchivos = new javax.swing.JMenu();
        menuListado = new javax.swing.JMenuItem();
        menuCargar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoxd.setBackground(new java.awt.Color(255, 255, 255));
        fondoxd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N

        jMenuBar1.setBorder(null);

        menuVehiculos.setText("Vehiculos");

        menuIngresarvechiculo.setText("Ingresar Vehiculo");
        menuIngresarvechiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarvechiculoActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuIngresarvechiculo);

        menuRetirtarvehiculo.setText("Retirar Vehiculo");
        menuRetirtarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRetirtarvehiculoActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuRetirtarvehiculo);

        MenuCrearUsuario.setText("Crear nuevo Usuario");
        MenuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearUsuarioActionPerformed(evt);
            }
        });
        menuVehiculos.add(MenuCrearUsuario);

        jMenuBar1.add(menuVehiculos);

        menuArchivos.setText("Archivos");

        menuListado.setText("Lista de vehiculos");
        menuListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoActionPerformed(evt);
            }
        });
        menuArchivos.add(menuListado);

        menuCargar.setText("Cargar datos");
        menuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCargarActionPerformed(evt);
            }
        });
        menuArchivos.add(menuCargar);

        jMenuBar1.add(menuArchivos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoxd, javax.swing.GroupLayout.PREFERRED_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoxd, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIngresarvechiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarvechiculoActionPerformed
        // TODO add your handling code here:
        
        setSize (800,450);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(true);
        panelcrearCrearUsuario.setVisible(false);
        
        
        
    }//GEN-LAST:event_menuIngresarvechiculoActionPerformed

    private void menuRetirtarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRetirtarvehiculoActionPerformed
        // TODO add your handling code here:
        setSize (800,450);
        panelretirarvehiculo.setVisible(true);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
        panelcrearCrearUsuario.setVisible(false);
        
    }//GEN-LAST:event_menuRetirtarvehiculoActionPerformed

    private void menuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargarActionPerformed
        // TODO add your handling code here:
        setSize (800,450);
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(true);
        panellistavehiculos.setVisible(false);
        panelcrearCrearUsuario.setVisible(false);
    }//GEN-LAST:event_menuCargarActionPerformed

    private void menuListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoActionPerformed
        // TODO add your handling code here:
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(true);
        panelcrearCrearUsuario.setVisible(false);
    }//GEN-LAST:event_menuListadoActionPerformed

    private void MenuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearUsuarioActionPerformed
        // TODO add your handling code here:
        panelretirarvehiculo.setVisible(false);
        panelingresarvehiculo.setVisible(false);
        panelcargarvehiculos.setVisible(false);
        panellistavehiculos.setVisible(false);
        panelcrearCrearUsuario.setVisible(true);
    }//GEN-LAST:event_MenuCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCrearUsuario;
    private javax.swing.JLabel fondoxd;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArchivos;
    private javax.swing.JMenuItem menuCargar;
    private javax.swing.JMenuItem menuIngresarvechiculo;
    private javax.swing.JMenuItem menuListado;
    private javax.swing.JMenuItem menuRetirtarvehiculo;
    private javax.swing.JMenu menuVehiculos;
    // End of variables declaration//GEN-END:variables

    


    
}
